// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxotncamcnpypxckeupz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4b3RuY2FtY25weXB4Y2tldXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDAzODEsImV4cCI6MjA2ODUxNjM4MX0.P6vvvJTGNjTcntXhJU8FeeA7mRWQzbfRxFWgKrdc_FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});